default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 10
  username: murmur
  password: Murmur@2025!
  host: 127.0.0.1

development:
  <<: *default
  database: murmur_dev

test:
  <<: *default
  database: murmur_test

production:
  <<: *default
  database: murmur_prod
  username: <%= ENV.fetch("MYSQL_USERNAME", "root") %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  host: <%= ENV.fetch("MYSQL_HOST", "127.0.0.1") %>

